# 679.Напишіть функцію, яка виконує ділення двох цілих чисел (числа вводяться в одному рядку 
# через пропуск.). Необхідно написати програму, яка запускає цю функцію, і, у разі помилки 
# (ділення на нуль), генерується виняток ZeroDivisionError і виводить його ім’я як у вихідних 
# даних. В разі успішної дії ділення, має виводитись результат і повідомлення OK. У будь-якому 
# випадку в кінці роботи програми виводиться повідомлення Done.
'''
Вхідні дані:
10 4
5 0

Вихідні дані:
2.5
OK
Done
ZeroDivisionError
Done
'''
def divide(x, y):
    try:
        result = x / y
    except ZeroDivisionError:
        print("ZeroDivisionError")
    else:
        print(result)
        print("OK")
    finally:
        print("Done")
divide(10, 4)
divide(5, 0)